name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
        
    - name: Update npm dependencies
      run: |
        # Update package.json dependencies
        npm update
        npm audit fix --audit-level=moderate
        
    - name: Run tests after updates
      run: |
        npm test -- --passWithNoTests --detectOpenHandles --forceExit
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates:
          
          ### Node.js Dependencies
          - Updated npm packages to latest compatible versions
          - Applied security fixes where available
          
          ### Verification
          - ✅ All tests pass
          - ✅ No breaking changes detected
          - ✅ Security vulnerabilities addressed
          
          Please review the changes and merge if everything looks good.
        branch: chore/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          chore